"use strict";
let a = 5;
let b = 3;
let sum = a + b;
let difference = a - b;
let product = a * b;
let quotient = a / b;
console.log(`The sum of ${a} and ${b} is ${sum}.`);
console.log(`The difference between ${a} and ${b} is ${difference}.`);
console.log(`The product of ${a} and ${b} is ${product}.`);
console.log(`The quotient of ${a} and ${b} is ${quotient}.`);
